### ISSUE TITLE
Getting data weather data to  display according to preferences

### ISSUE THREAD

**Issue by mocktarissa** [lastmaj/mobile-news-app#2]

**Comment by lastmaj** [comment]
More details ? 
Can you share the API you're using ? 
You can always follow the model I did, I just used the query params for api endpoints as shared preferences that the user can change in the settings menu.

**Comment by mocktarissa** [comment]
The api i used takes cities as parameters not countries as a whole so i just left a default string with a static city

**Comment by lastmaj** [comment]
I'll look into it
